---
lib/test_map/config.rb:
- test/test_map/config_test.rb
lib/test_map/errors.rb:
- test/test_map/errors_test.rb
- test/test_map/file_recorder_test.rb
lib/test_map/file_recorder.rb:
- test/test_map/config_test.rb
- test/test_map/errors_test.rb
- test/test_map/file_recorder_test.rb
- test/test_map/mapping_test.rb
- test/test_map/report_test.rb
- test/test_map_test.rb
lib/test_map/mapping.rb:
- test/test_map/mapping_test.rb
lib/test_map/plugins/minitest.rb:
- test/test_map/config_test.rb
- test/test_map/errors_test.rb
- test/test_map/file_recorder_test.rb
- test/test_map/mapping_test.rb
- test/test_map/report_test.rb
- test/test_map_test.rb
lib/test_map/report.rb:
- test/test_map/report_test.rb
test/test_map/config_test.rb:
- test/test_map/config_test.rb
test/test_map/file_recorder_test.rb:
- test/test_map/file_recorder_test.rb
test/test_map/mapping_test.rb:
- test/test_map/mapping_test.rb
test/test_map/report_test.rb:
- test/test_map/report_test.rb
