---
lib/test_map/minitest/plugin.rb:
- test/test_map_test.rb
- test/test_map/errors_test.rb
- test/test_map/report_test.rb
lib/test_map/file_recorder.rb:
- test/test_map_test.rb
- test/test_map/errors_test.rb
- test/test_map/report_test.rb
lib/test_map/errors.rb:
- test/test_map_test.rb
- test/test_map/errors_test.rb
- test/test_map/report_test.rb
test/test_map/report_test.rb:
- test/test_map_test.rb
- test/test_map/errors_test.rb
- test/test_map/report_test.rb
lib/test_map/report.rb:
- test/test_map_test.rb
- test/test_map/errors_test.rb
- test/test_map/report_test.rb
