# frozen_string_literal: true

require 'minitest/test_task'
require 'test_map/test_task'

# require 'rake/testtask'
# Rake::TestTask.new do |t|
#   t.libs << 'test'
#   t.test_files = FileList['test/**/*_test.rb']
# end
Minitest::TestTask.create
TestMap::TestTask.create

task default: :test
