---

name: Main Pipeline

on:
  workflow_dispatch:

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    needs: [lint, test, verify]
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby
      - uses: rubygems/release-gem@v1
